### PR TITLE
Added interval constants and updated code

### PR DESCRIPTION
**Pull request by WimWidgets**

### CODE REVIEW

**Comment by jimhigson** [comment]
Thanks!

**Comment by WimWidgets** [comment]
When will 1.0.3 be available on npmjs?

**Comment by jimhigson** [comment]
I should be able to push it in a few hours. In the meantime, you can use
‘npm link’ command to get the new version now by adding a symlink (or
whatever Windows has) to a git clone in your node modules.

**Comment by jimhigson** [comment]
Now on npm

**Pull request merged**
